import { useCallback, useEffect, useMemo, useState } from 'react'
import { LanguageContext } from './languageCore'

const STORAGE_KEY = 'lz_language'

const translations = {
  en: {
    loading: 'Loading...',
    cancel: 'Cancel',
    edit: 'Edit',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    clear: 'Clear',
    date: 'Date',
    time: 'Time',
    status: 'Status',
    actions: 'Actions',
    players: 'Players',
    total: 'Total',
    max: 'max',
    username: 'Username',
    password: 'Password',
    loginSubtitle: 'Sign in to your account',
    registerSubtitle: 'Create a new account',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    register: 'Register',
    creatingAccount: 'Creating account...',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    hasAccount: 'Already have an account?',
    signInHere: 'Sign in here',
    usernameRequired: 'Username is required',
    usernameMin: 'Username must be at least 3 characters',
    usernameChars: 'Username can only contain letters, numbers, and underscores',
    passwordRequired: 'Password is required',
    passwordMin: 'Password must be at least 6 characters',
    loginFailed: 'Login failed. Please try again.',
    registerFailed: 'Registration failed. Please try again.',
    genericError: 'An error occurred. Please try again later.',
    viewProfile: 'View profile',
    myReservations: 'My Reservations',
    browseGroups: 'Browse Groups',
    myGroups: 'My Groups',
    adminReservations: 'Admin Reservations',
    logout: 'Logout',
    customer: 'customer',
    admin: 'admin',
    notificationTitle: 'Notifications',
    makeReservation: 'Make Reservation',
    reservationCount: '{{count}} item{{plural}}',
    noReservations: 'No reservations yet',
    noReservationsHint: 'Click "Make Reservation" to book your first session.',
    cancelReservationConfirm: 'Cancel this reservation?',
    cancelGroupConfirm: 'Cancel this group?',
    cancelling: 'Cancelling...',
    group: 'Group',
    full: 'Full',
    newReservation: 'New Reservation',
    createOpenGroup: 'Create Open Group',
    markAsOpenGroup: 'Mark as Open Group',
    openForExternalMembers: 'Open for external members',
    reservationName: 'Reservation Name',
    groupName: 'Group Name',
    reservationNamePlaceholder: 'e.g. Birthday Party, Friday Night...',
    groupNamePlaceholder: 'e.g. Friday Night Crew...',
    selectDateFirst: 'Select date first',
    loadingSlots: 'Loading...',
    slotFull: 'Full',
    myTeam: 'My Team',
    externalJoin: 'External Join',
    createGroup: 'Create Group',
    creating: 'Creating...',
    nameTooShort: 'Name must be at least 2 characters.',
    selectDate: 'Please select a date.',
    actionFailed: 'Action failed',
    reviewAdminReservations: 'Review reservations and manage approvals or cancellations',
    all: 'All',
    active: 'active',
    cancelled: 'cancelled',
    completed: 'completed',
    noReservationsFound: 'No reservations found',
    reservation: 'Reservation',
    approve: 'Approve',
    approving: 'Approving...',
    approveConfirm: 'Approve this reservation?',
    cancelAdminConfirm: 'Cancel this reservation?',
    failedLoadReservations: 'Failed to load reservations',
    reservationApproved: 'Reservation approved.',
    reservationCancelled: 'Reservation cancelled.',
    manageGroups: 'Manage your group reservations and approve join requests',
    noGroups: "You haven't created any groups",
    noGroupsHint: 'Go to My Reservations and toggle "Mark as Open Group" to create one.',
    requests: 'Requests',
    noJoinRequests: 'No join requests yet.',
    reject: 'Reject',
    open: 'Open',
    noOpenGroups: 'No open groups found',
    noOpenGroupsHint: 'Try changing your filters or check back later.',
    browseGroupsSubtitle: 'Find a group and send a join request to the leader',
    searchByName: 'Search by name',
    groupNameSearchPlaceholder: 'Group name...',
    search: 'Search',
    leader: 'Leader',
    noSpotsLeft: 'No spots left',
    spotsLeft: '{{count}} spot{{plural}} left',
    yourGroup: 'Your Group',
    joinGroupTitle: 'Join "{{name}}"',
    joinRequestHint: 'Your request will be sent to the group leader for approval.',
    joinPlayerQuestion: 'How many players are you bringing?',
    sendRequest: 'Send Request',
    sending: 'Sending...',
    requestSent: 'Request sent! Waiting for leader approval.',
    failedJoinRequest: 'Failed to send join request',
    searchGroups: 'Search groups',
    availableOnly: 'Available only',
    wantToJoin: 'I Want to Join',
    joined: 'Joined',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
  },
  tr: {
    loading: 'Yükleniyor...',
    cancel: 'İptal',
    edit: 'Düzenle',
    saveChanges: 'Değişiklikleri Kaydet',
    saving: 'Kaydediliyor...',
    clear: 'Temizle',
    date: 'Tarih',
    time: 'Saat',
    status: 'Durum',
    actions: 'İşlemler',
    players: 'Oyuncular',
    total: 'Toplam',
    max: 'maks',
    username: 'Kullanıcı adı',
    password: 'Şifre',
    loginSubtitle: 'Hesabına giriş yap',
    registerSubtitle: 'Yeni hesap oluştur',
    signIn: 'Giriş Yap',
    signingIn: 'Giriş yapılıyor...',
    register: 'Kayıt Ol',
    creatingAccount: 'Hesap oluşturuluyor...',
    noAccount: 'Hesabın yok mu?',
    registerHere: 'Buradan kayıt ol',
    hasAccount: 'Zaten hesabın var mı?',
    signInHere: 'Buradan giriş yap',
    usernameRequired: 'Kullanıcı adı zorunlu',
    usernameMin: 'Kullanıcı adı en az 3 karakter olmalı',
    usernameChars: 'Kullanıcı adı sadece harf, rakam ve alt çizgi içerebilir',
    passwordRequired: 'Şifre zorunlu',
    passwordMin: 'Şifre en az 6 karakter olmalı',
    loginFailed: 'Giriş başarısız. Lütfen tekrar dene.',
    registerFailed: 'Kayıt başarısız. Lütfen tekrar dene.',
    genericError: 'Bir hata oluştu. Lütfen daha sonra tekrar dene.',
    viewProfile: 'Profili görüntüle',
    myReservations: 'Rezervasyonlarım',
    browseGroups: 'Gruplara Göz At',
    myGroups: 'Gruplarım',
    adminReservations: 'Admin Rezervasyonları',
    logout: 'Çıkış Yap',
    customer: 'müşteri',
    admin: 'admin',
    notificationTitle: 'Bildirimler',
    makeReservation: 'Rezervasyon Yap',
    reservationCount: '{{count}} kayıt',
    noReservations: 'Henüz rezervasyon yok',
    noReservationsHint: 'İlk seansını ayırmak için "Rezervasyon Yap" butonuna tıkla.',
    cancelReservationConfirm: 'Bu rezervasyonu iptal etmek istiyor musun?',
    cancelGroupConfirm: 'Bu grubu iptal etmek istiyor musun?',
    cancelling: 'İptal ediliyor...',
    group: 'Grup',
    full: 'Dolu',
    newReservation: 'Yeni Rezervasyon',
    createOpenGroup: 'Açık Grup Oluştur',
    markAsOpenGroup: 'Açık Grup Olarak İşaretle',
    openForExternalMembers: 'Dış katılımcılara açık',
    reservationName: 'Rezervasyon Adı',
    groupName: 'Grup Adı',
    reservationNamePlaceholder: 'örn. Doğum günü, cuma gecesi...',
    groupNamePlaceholder: 'örn. Cuma gecesi ekibi...',
    selectDateFirst: 'Önce tarih seç',
    loadingSlots: 'Yükleniyor...',
    slotFull: 'Dolu',
    myTeam: 'Takımım',
    externalJoin: 'Dış Katılım',
    createGroup: 'Grup Oluştur',
    creating: 'Oluşturuluyor...',
    nameTooShort: 'Ad en az 2 karakter olmalıdır.',
    selectDate: 'Lütfen bir tarih seçin.',
    actionFailed: 'İşlem başarısız',
    reviewAdminReservations: 'Rezervasyonları incele, onayla veya iptal et',
    all: 'Tümü',
    active: 'aktif',
    cancelled: 'iptal',
    completed: 'tamamlandı',
    noReservationsFound: 'Rezervasyon bulunamadı',
    reservation: 'Rezervasyon',
    approve: 'Onayla',
    approving: 'Onaylanıyor...',
    approveConfirm: 'Bu rezervasyonu onaylamak istiyor musun?',
    cancelAdminConfirm: 'Bu rezervasyonu iptal etmek istiyor musun?',
    failedLoadReservations: 'Rezervasyonlar yüklenemedi',
    reservationApproved: 'Rezervasyon onaylandı.',
    reservationCancelled: 'Rezervasyon iptal edildi.',
    manageGroups: 'Grup rezervasyonlarını yönet ve katılım isteklerini onayla',
    noGroups: 'Henüz grup oluşturmadın',
    noGroupsHint: 'Grup oluşturmak için Rezervasyonlarım sayfasında "Açık Grup Olarak İşaretle" seçeneğini aç.',
    requests: 'İstekler',
    noJoinRequests: 'Henüz katılım isteği yok.',
    reject: 'Reddet',
    open: 'Açık',
    noOpenGroups: 'Açık grup bulunamadı',
    noOpenGroupsHint: 'Filtreleri değiştirmeyi deneyebilir veya daha sonra tekrar bakabilirsin.',
    browseGroupsSubtitle: 'Bir grup bul ve lidere katılım isteği gönder',
    searchByName: 'Ada göre ara',
    groupNameSearchPlaceholder: 'Grup adı...',
    search: 'Ara',
    leader: 'Lider',
    noSpotsLeft: 'Boş yer yok',
    spotsLeft: '{{count}} yer kaldı',
    yourGroup: 'Senin Grubun',
    joinGroupTitle: '"{{name}}" grubuna katıl',
    joinRequestHint: 'İsteğin onay için grup liderine gönderilecek.',
    joinPlayerQuestion: 'Kaç oyuncu getiriyorsun?',
    sendRequest: 'İstek Gönder',
    sending: 'Gönderiliyor...',
    requestSent: 'İstek gönderildi! Lider onayı bekleniyor.',
    failedJoinRequest: 'Katılım isteği gönderilemedi',
    searchGroups: 'Grup ara',
    availableOnly: 'Sadece uygun olanlar',
    wantToJoin: 'Katılmak İstiyorum',
    joined: 'Katıldın',
    pending: 'Beklemede',
    approved: 'Onaylandı',
    rejected: 'Reddedildi',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY)
    return stored === 'tr' || stored === 'en' ? stored : 'en'
  })

  useEffect(() => {
    document.documentElement.lang = language
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const setLanguage = useCallback((nextLanguage) => {
    if (nextLanguage === 'tr' || nextLanguage === 'en') {
      setLanguageState(nextLanguage)
    }
  }, [])

  const t = useCallback((key, params = {}) => {
    const template = translations[language][key] || translations.en[key] || key
    return Object.entries(params).reduce(
      (text, [name, value]) => text.replaceAll(`{{${name}}}`, String(value)),
      template
    )
  }, [language])

  const locale = language === 'tr' ? 'tr-TR' : 'en-US'

  const value = useMemo(() => ({ language, setLanguage, t, locale }), [language, setLanguage, t, locale])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
